### ISSUE TITLE
I can't read data in MS-access, works OK in EID.Wrapper.Console-utility

### ISSUE THREAD

**Issue by InnieG** [jdt/EID.Wrapper#6] opened 2015-11-17 12:21 UTC
Hi jdt

I have an MS-access DB on a Windows 7 Pro 32-bit with Office 2010 32-bit.  .Net framework, eID software and eID wrapper 32-bit installed.  When I read an ID in the MS-access DB it gives the message that the ID is not valid.  I can read the ID fine with the EID.Wrapper.Console-utility and eID viewer.

When I open the database on my other computer Windows 8.1 Pro 64-bit with office 2013 64-bit, the ID is read OK. (.Net framework, eID software and eID wrapper 64-bit installed)

You mentioned that this could be a problem with the COM-registration, but how can I fix this?

Thanks in advance and kind regards
Inne

**Comment by JohanRVT** [comment] 2015-11-18 08:32
There is a difference between Access 64 Bit and Access 32 bit and can U post your vba Code that U use? We don't use Access 64 because ther is a lot off ftuff that isn't working any more.

**Comment by InnieG** [comment] 2015-11-18 09:21
Here the code I use:

Dim wrapper As New EID_Wrapper.wrapper
Dim data As EID_Wrapper.CardData

Set data = wrapper.GetCardData()
If data.FirstCard Is Nothing Then
        MsgBox ("No valid card found!")
Else
        If data.FirstCard.ZipCode = "xxxx" Then
           MsgBox ("Welkom inwoner")
        Else
            MsgBox ("Deze persoon is geen inwoner")
        End If

```
End If
```

**Comment by jdt** [comment] 2015-11-26 19:16
If the console utility works, the issue is most likely due to the registration of the DLL. Where does the message appear that the ID is not valid? The wrapper itself does not show any messages so I'm curious where this comes from.

**Comment by InnieG** [comment] 2015-11-27 11:53
In the code the MsgBox ("No valid card found") is always triggered on the 32-bit machine, same database and same ID card on the 64-bit machine triggers MsgBox("Deze persoon is geen inwoner") which is the correct logical path

**Comment by jdt** [comment] 2015-11-27 12:16
You get the "No valid card found" because data.FirstCard is nothing. That could mean that an exception occurred while reading the cards. Check the data.CardDataStatus and see if that is set to Error, in which case you should be able to find the exact error message via the data.Error-property, as outlined in the documentation at https://github.com/jdt/EID.Wrapper#checking-for-exceptions

**Comment by InnieG** [comment] 2015-11-27 13:04
Hi Jesper

The CardDataStatus is not set to Error, it is set to 2 (on both machines).  Not sure what this means.

**Comment by jdt** [comment] 2015-12-08 20:29
Try comparing CardDataStatus to the enum and show a message
If data.CardDataStatus = CardDataStatus.Error Then
MsgBox ("Status is error")
...etc 
and see what the status is.

**Comment by jdt** [comment] 2015-12-31 10:52
I'm going to close this as there have been no further replies. I've just pushed out a new version of the wrapper that is more robust and seems to fix an error that I cannot reproduce but is very real, so I would suggest you try the new version and see if that works for you. I'd be happy to assist if any more issues arise.

**Closed as completed by jdt** 2015-12-31 10:52 UTC

**Comment by InnieG** [comment] 2016-01-04 17:48
Hi Jesper

Thanks for the updated release, this fixed my problem.

Kind regards
Inne

Van: Jesper De Temmerman [mailto:notifications@github.com]
Verzonden: donderdag 31 december 2015 11:52
Aan: jdt/EID.Wrapper EID.Wrapper@noreply.github.com
CC: Inne Gebruers Inne.Gebruers@lille.be
Onderwerp: Re: [EID.Wrapper] I can't read data in MS-access, works OK in EID.Wrapper.Console-utility (#6)

I'm going to close this as there have been no further replies. I've just pushed out a new version of the wrapper that is more robust and seems to fix an error that I cannot reproduce but is very real, so I would suggest you try the new version and see if that works for you. I'd be happy to assist if any more issues arise.
